### ISSUE TITLE
CREATE INDEX does not block table reads

### ISSUE THREAD

**Issue by seanpascoe** [fly-apps/safe-ecto-migrations#15]
Folks at my company have been passing this repo and associated article around like it's gospel, but I'm pretty sure you're wrong on creating postgres indexes and blocking table reads:

> Creating an index will block both reads and writes in Postgres. 

CREATE INDEX will block table writes but not _reads_ in postgres

> With Postgres, instead create the index concurrently which does not block reads.

creating the index concurrently will not block _writes_.  

From the [postgresql docs regarding CONCURRENTLY](https://www.postgresql.org/docs/16/sql-createindex.html)

> When this option is used, PostgreSQL will build the index without taking any locks that prevent concurrent inserts, updates, or deletes on the table; whereas a standard index build locks out writes (but not reads) on the table until it's done. There are several caveats to be aware of when using this option — see [Building Indexes Concurrently](http://www.postgresql.org/docs/current/interactive/sql-createindex.html#SQL-CREATEINDEX-CONCURRENTLY).

**Comment by dbernheisel** [comment]
Thanks, there's definitely an inconsistency here. The example is correct in stating "which will block writes" but the description says (incorrectly) it will also block reads. This must've been some copy-paste error; sorry about that. I'll get a PR up to resolve.

**Comment by dbernheisel** [comment]
Also see some notes I left in #8

**Comment by dbernheisel** [comment]
fixed!
