### ISSUE TITLE
Add hint to tune down `:migration_advisory_lock_retry_interval_ms` in `dev` environment when using `:pg_advisory_lock`

### ISSUE THREAD

**Issue by cgrothaus** [fly-apps/safe-ecto-migrations#6]
In the _"Adding an index"_ section it is advised to configure the Repo to use advisory locks with `:pg_advisory_lock`. This can cause long phoenix request delays (5s :open_mouth:) in phoenix `dev` environment. This is due to `Phoenix.Ecto.CheckRepoStatus` calling `Ecto.Migrator.migrations/1`, which runs under a migration lock. When “Ecto cannot obtain the lock due to another instance occupying the lock, Ecto will wait for 5 seconds”. In `dev` environment, with `CheckRepoStatus` plug, you just need two web requests to hit your phoenix server at the very same time to get into that situation. We stumbled into it with a JS app that, after load, fired two simultaneous GraphQL requests. One of them would take 5s. 

I [already asked in Elixir Forum](https://elixirforum.com/t/does-phoenix-ecto-checkrepostatus-callling-ecto-migrator-migrations-1-need-to-run-under-an-ecto-migration-lock/52170) whether it is necessary that this convenience plug runs under a migration lock.

We worked around the problem by tuning down the `:migration_advisory_lock_retry_interval_ms` setting from its default value of 5000 ms to 10 ms (just in `dev`). Unless there are better options, maybe you can add that hint to the guide?

**Comment by dbernheisel** [comment]
Thanks for bringing this up.

There might be a way to pass in the retry options directly to `Ecto.Migrator.migrations/3` but `CheckRepoStatus` uses the arity 1 function which doesn't accept opts. There might need to be some adjustment to have Phoenix.Ecto do this transparently.

In the meantime, retrying more often in dev is probably the best way to approach this. We can add a note to the guide.
